# Restore the TARGET and HOST variables
TARGET_CC:=$(OLD_TARGET_CC)
TARGET_CXX:=$(OLD_TARGET_CXX)
TARGET_AR:=$(OLD_TARGET_AR)
TARGET_LD:=$(OLD_TARGET_LD)
HOST_CC:=$(OLD_HOST_CC)
HOST_CXX:=$(OLD_HOST_CXX)
HOST_AR:=$(OLD_HOST_AR)
TARGET_GLOBAL_CFLAGS:=$(OLD_TARGET_GLOBAL_CFLAGS)

