#
# Copyright (C) 2008 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This list defines which projects are now working with clang. We will add more
# projects here as they get support for building with clang and eventually
# there will be no need for it anymore once everything gets ported.
clang_supported_targets := \
  AudioHardwareRecord \
  AudioHardwareRecordLoop \
  AudioInRecord \
  BasicHashtable_test \
  BlobCache_test \
  BufferQueue_test \
  EGL_test \
  FileCheck \
  InputChannel_test \
  InputDispatcher_test \
  InputEvent_test \
  InputPublisherAndConsumer_test \
  InputReader_test \
  Looper_test \
  NativeMediaTest_SL \
  NativeMediaTest_XA \
  ObbFile_test \
  SRecTest \
  SRecTestAudio \
  String8_test \
  SurfaceMediaSource_test \
  SurfaceTexture_test \
  Unicode_test \
  Vector_test \
  ZipFileRO_test \
  aapt \
  acp \
  adb \
  adbd \
  add-property-tag \
  aidl \
  angeles \
  app_process \
  applypatch \
  applypatch_static \
  aprotoc \
  ash \
  atrace \
  atree \
  audio.primary.default \
  audio.primary.goldfish \
  audio.primary.herring \
  audio.usb.default \
  audio_policy.default \
  audio_policy.herring \
  audio_policy.stub \
  audioloop \
  backup_helper_test \
  badblocks \
  badblocks_host \
  bb2sym \
  bb_dump \
  bbprof \
  bcc \
  bcinfo \
  binderAddInts \
  bison \
  bootanimation \
  bsdiff \
  bspatch \
  btool \
  bugreport \
  cachegrind-x86-linux \
  callgrind-x86-linux \
  camera.goldfish \
  camera2_hal_tests \
  camera_metadata_tests \
  charger \
  check-lost+found \
  check_prereq \
  check_stack \
  check_trace \
  checkmodule \
  checkpolicy \
  chkcon \
  clang \
  clang-tblgen \
  cmu2nuance \
  codec \
  common_time \
  corrupt_gdt_free_blocks \
  coverage \
  cpueater \
  cpufeatures \
  cpustats \
  crasher \
  create_test_dmtrace \
  cts-usb-accessory \
  cts_audio_quality \
  cts_audio_quality_test \
  daemonize \
  dalvik-vm-unit-tests \
  dalvikvm \
  dbus-daemon \
  dbus-monitor \
  dbus-send \
  debuggerd \
  decoder \
  dexdump \
  dexlist \
  dexopt \
  dhcpcd \
  dictTest \
  directiotest \
  dmg_fp \
  dmtracedump \
  dnsmasq \
  dnssd \
  drd-x86-linux \
  drmserver \
  dump_regions \
  dumpstate \
  dumpsys \
  dvz \
  e2fsck \
  e2fsck_host \
  edify \
  elftree \
  emugen \
  emulator_renderer \
  etc1tool \
  exc_dump \
  ext2simg \
  ext4fixup \
  fastboot \
  fatblock \
  flash_image \
  fs_config \
  fs_get_stats \
  fs_mgr \
  fsck_msdos \
  gccdemangle_test \
  gdbjithelper \
  genext2fs \
  glsl_compiler \
  gps.goldfish \
  gpttool \
  gralloc.default \
  gralloc.goldfish \
  grxmlcompile \
  gtest-death-test_test \
  gtest-filepath_test \
  gtest-linked_ptr_test \
  gtest-message_test \
  gtest-options_test \
  gtest-port_test \
  gtest-test-part_test \
  gtest-typed-test2_test \
  gtest-typed-test_test \
  gtest_environment_test \
  gtest_no_test_unittest \
  gtest_pred_impl_unittest \
  gtest_prod_test \
  gtest_repeat_test \
  gtest_stress_test \
  gtest_unittest \
  gzip \
  helgrind-x86-linux \
  hist_trace \
  hprof-conv \
  hwcColorEquiv \
  hwcCommit \
  hwcRects \
  hwcStress \
  hwcomposer.default \
  icudata \
  img2simg \
  imgdiff \
  init \
  installd \
  invoke_mock_media_player \
  iontest \
  ip \
  ip-up-vpn \
  ip6tables \
  iptables \
  jdwpspy \
  jpeg_bench \
  keymaster_test \
  keystore \
  keystore.default \
  keystore_cli \
  kfmapp \
  latencytop \
  lib64EGL_translator \
  lib64GLES_CM_translator \
  lib64GLES_V2_translator \
  lib64GLESv1_dec \
  lib64GLESv2_dec \
  lib64GLcommon \
  lib64OpenglCodecCommon \
  lib64OpenglOsUtils \
  lib64OpenglRender \
  lib64_renderControl_dec \
  lib64cutils \
  lib64log \
  lib64utils \
  libEGL \
  libEGL_emulation \
  libEGL_translator \
  libESR_Portable \
  libESR_Shared \
  libETC1 \
  libFFTEm \
  libFLAC \
  libFraunhoferAAC \
  libGLES_CM_translator \
  libGLES_V2_translator \
  libGLES_android \
  libGLES_trace \
  libGLESv1_CM \
  libGLESv1_CM_emulation \
  libGLESv1_dec \
  libGLESv1_enc \
  libGLESv2 \
  libGLESv2_dec \
  libGLESv2_emulation \
  libGLESv2_enc \
  libGLcommon \
  libLLVMARMAsmParser \
  libLLVMARMAsmPrinter \
  libLLVMARMCodeGen \
  libLLVMARMDesc \
  libLLVMARMDisassembler \
  libLLVMARMInfo \
  libLLVMAnalysis \
  libLLVMArchive \
  libLLVMAsmParser \
  libLLVMAsmPrinter \
  libLLVMBitReader \
  libLLVMBitReader_2_7 \
  libLLVMBitReader_3_0 \
  libLLVMBitWriter \
  libLLVMBitWriter_2_9 \
  libLLVMBitWriter_2_9_func \
  libLLVMCodeGen \
  libLLVMCore \
  libLLVMInstCombine \
  libLLVMInstrumentation \
  libLLVMJIT \
  libLLVMLinker \
  libLLVMMC \
  libLLVMMCParser \
  libLLVMMipsAsmPrinter \
  libLLVMMipsCodeGen \
  libLLVMMipsDesc \
  libLLVMMipsInfo \
  libLLVMScalarOpts \
  libLLVMSelectionDAG \
  libLLVMSupport \
  libLLVMTableGen \
  libLLVMTarget \
  libLLVMTransformUtils \
  libLLVMVectorize \
  libLLVMWrap \
  libLLVMX86AsmParser \
  libLLVMX86AsmPrinter \
  libLLVMX86CodeGen \
  libLLVMX86Desc \
  libLLVMX86Disassembler \
  libLLVMX86Info \
  libLLVMX86Utils \
  libLLVMipa \
  libLLVMipo \
  libMesa \
  libOMX.SEC.AVC.Decoder \
  libOMX.SEC.AVC.Encoder \
  libOMX.SEC.M4V.Decoder \
  libOMX.SEC.M4V.Encoder \
  libOpenMAXAL \
  libOpenSLES \
  libOpenSLESUT \
  libOpenglCodecCommon \
  libOpenglOsUtils \
  libOpenglRender \
  libOpenglSystemCommon \
  libRS \
  libRSDriver \
  libSEC_OMX_Core \
  libSEC_OMX_Vdec \
  libSEC_OMX_Venc \
  libSR_AcousticModels \
  libSR_AcousticState \
  libSR_AudioIn \
  libSR_Core \
  libSR_EventLog \
  libSR_G2P \
  libSR_Grammar \
  libSR_Nametag \
  libSR_Recognizer \
  libSR_Semproc \
  libSR_Session \
  libSR_Vocabulary \
  libWnnEngDic \
  libWnnJpnDic \
  lib_renderControl_dec \
  lib_renderControl_enc \
  libaah_rtp \
  libandroid \
  libandroid_runtime \
  libandroid_servers \
  libandroidfw \
  libapplypatch \
  libastl \
  libastl_host \
  libaudioeffect_jni \
  libaudioflinger \
  libaudiohw_legacy \
  libaudiopolicy_legacy \
  libaudiopreprocessing \
  libaudioutils \
  libbcc \
  libbccCompilerRT \
  libbccExecutionEngine \
  libbccHelper \
  libbccTransforms \
  libbcinfo \
  libbinder \
  libbordeaux \
  libbundlewrapper \
  libbz \
  libc \
  libc_common \
  libc_malloc_debug_leak \
  libc_malloc_debug_qemu \
  libc_nomalloc \
  libcamera_client \
  libcamera_metadata \
  libcameraanalyzer \
  libcameraservice \
  libchromium_net \
  libclangARCMigrate \
  libclangAST \
  libclangAnalysis \
  libclangBasic \
  libclangCodeGen \
  libclangDriver \
  libclangEdit \
  libclangFrontend \
  libclangFrontendTool \
  libclangLex \
  libclangParse \
  libclangRewrite \
  libclangSema \
  libclangSerialization \
  libclangStaticAnalyzerCheckers \
  libclangStaticAnalyzerCore \
  libclangStaticAnalyzerFrontend \
  libcolorchecker \
  libcommon_time_client \
  libcompiler-rt \
  libcoregrind-x86-linux \
  libcorkscrew \
  libcpustats \
  libcrypto \
  libcrypto_static \
  libctest \
  libcts_audio_quality \
  libcts_jni \
  libctsmediastress_jni \
  libctspermission_jni \
  libctsverifier_jni \
  libcutils \
  libcv \
  libcvaux \
  libcvhighgui \
  libcvml \
  libcxcore \
  libdbus \
  libdbus-tools-common \
  libdefcontainer_jni \
  libdex \
  libdexdump_static \
  libdiskconfig \
  libdiskconfig_host \
  libdiskusage \
  libdl \
  libdownmix \
  libdrm1 \
  libdrm1_jni \
  libdrmframework \
  libdrmframework_jni \
  libdrmframeworkcommon \
  libdrmpassthruplugin \
  libdrmutility \
  libdw \
  libdwfl \
  libdynamic_annotations \
  libebl \
  libedify \
  libeffects \
  libelf \
  libembunit \
  libemoji \
  libevent \
  libexif \
  libexif_jni \
  libexpat \
  libexpat_static \
  libext \
  libext2_blkid \
  libext2_blkid_host \
  libext2_com_err \
  libext2_com_err_host \
  libext2_e2p \
  libext2_e2p_host \
  libext2_profile \
  libext2_profile_host \
  libext2_uuid \
  libext2_uuid_host \
  libext2fs \
  libext2fs_host \
  libext4 \
  libext4_utils \
  libext6 \
  libfdlibm \
  libfilterfw \
  libfilterfw_jni \
  libfilterfw_native \
  libfilterpack_base \
  libfilterpack_imageproc \
  libfmradio \
  libfs_mgr \
  libfst \
  libft2 \
  libfwdlock-common \
  libfwdlock-converter \
  libfwdlock-decoder \
  libfwdlockengine \
  libgabi++ \
  libgccdemangle \
  libgif \
  libgl2jni \
  libglTest \
  libgldualjni \
  libgljni \
  libglperf \
  libgsm \
  libgtest \
  libgtest_host \
  libgtest_main \
  libgtest_main_host \
  libgui \
  libhardware \
  libhardware_legacy \
  libharfbuzz \
  libhost \
  libhwcTest \
  libhwui \
  libhyphenation \
  libicui18n \
  libicuuc \
  libinput \
  libinstalld \
  libinvensense_hal \
  libion \
  libip4tc \
  libip6tc \
  libiprouteutil \
  libipsec \
  libjavacore \
  libjni_eglfence \
  libjni_latinime \
  libjni_latinime_static \
  libjni_legacymosaic \
  libjni_mosaic \
  libjni_pinyinime \
  libjnigraphics \
  libjnitest \
  libjpeg \
  libkeystore \
  libkeystore_client \
  liblinenoise \
  liblog \
  liblzf \
  libm \
  libmcldARMInfo \
  libmcldARMTarget \
  libmcldCodeGen \
  libmcldLD \
  libmcldLDVariant \
  libmcldMC \
  libmcldMipsInfo \
  libmcldMipsTarget \
  libmcldSupport \
  libmcldTarget \
  libmcldX86Info \
  libmcldX86Target \
  libmdnssd \
  libmedia \
  libmedia_helper \
  libmedia_jni \
  libmedia_native \
  libmediaplayerservice \
  libminadbd \
  libmincrypt \
  libminelf \
  libminui \
  libminzip \
  libmllite \
  libmlplatform \
  libmtdutils \
  libmtp \
  libmulticlass_pa \
  libmusicbundle \
  libnative-media-jni \
  libnativehelper \
  libnbaio \
  libnetlink \
  libnetutils \
  libnfc \
  libnfc_jni \
  libnfc_ndef \
  libnl_2 \
  libopencv \
  libopenfst \
  libopengltest \
  libopensles_helper \
  libopenslestests \
  liboprofile_abi \
  liboprofile_db \
  liboprofile_op \
  liboprofile_popt \
  liboprofile_util \
  libpagemap \
  libpcap \
  libperf \
  libpixelflinger \
  libpixelflinger_static \
  libplatform_library_jni \
  libpng \
  libpower \
  libpowermanager \
  libprotobuf-cpp-2.3.0-full \
  libprotobuf-cpp-2.3.0-lite \
  libquake \
  librank \
  libreference-ril \
  libregex-re2 \
  libreplacemalloc_toolpreload-x86-linux \
  libreverb \
  libreverbwrapper \
  libril \
  librs_jni \
  librslib \
  librsloader \
  librtp_jni \
  libs3cjpeg \
  libsafe_iop \
  libsampleplugin \
  libscheduling_policy \
  libsecbasecomponent \
  libseccsc \
  libsecmfcdecapi \
  libsecmfcencapi \
  libsecosal \
  libselinux \
  libsensorservice \
  libsepol \
  libsimplejni \
  libskia \
  libskiagpu \
  libskiatess \
  libslang \
  libsonivox \
  libsoundpool \
  libspeex \
  libspeexresampler \
  libsqlite \
  libsqlite3_android \
  libsqlite3_phone_number_utils_test \
  libsqlite3_phonetic_string_utils_test \
  libsqlite_jni \
  libsrec_jni \
  libsrtp_static \
  libssh \
  libssl \
  libssl_static \
  libstagefright \
  libstagefright_aacenc \
  libstagefright_amrnb_common \
  libstagefright_amrnbdec \
  libstagefright_amrnbenc \
  libstagefright_amrwbdec \
  libstagefright_amrwbenc \
  libstagefright_avc_common \
  libstagefright_avcenc \
  libstagefright_chromium_http \
  libstagefright_color_conversion \
  libstagefright_enc_common \
  libstagefright_foundation \
  libstagefright_httplive \
  libstagefright_id3 \
  libstagefright_m4vh263dec \
  libstagefright_m4vh263enc \
  libstagefright_matroska \
  libstagefright_mp3dec \
  libstagefright_mpeg2ts \
  libstagefright_nuplayer \
  libstagefright_omx \
  libstagefright_rtsp \
  libstagefright_soft_aacdec \
  libstagefright_soft_aacenc \
  libstagefright_soft_amrdec \
  libstagefright_soft_amrnbenc \
  libstagefright_soft_amrwbenc \
  libstagefright_soft_flacenc \
  libstagefright_soft_g711dec \
  libstagefright_soft_h264dec \
  libstagefright_soft_h264enc \
  libstagefright_soft_mp3dec \
  libstagefright_soft_mpeg4dec \
  libstagefright_soft_mpeg4enc \
  libstagefright_soft_rawdec \
  libstagefright_soft_vorbisdec \
  libstagefright_soft_vpxdec \
  libstagefright_timedtext \
  libstagefright_yuv \
  libstdc++ \
  libstlport \
  libstlport_static \
  libstochastic_linear \
  libstorage \
  libsurfaceflinger \
  libsuspend \
  libsvoxpico \
  libsync \
  libsystem_server \
  libsysutils \
  libtestUtil \
  libtestplugin \
  libthread_db \
  libtinyalsa \
  libtinyxml \
  libtomcrypt \
  libtommath \
  libttscompat \
  libttspico \
  libttspico_engine \
  libublock \
  libui \
  libunz \
  libusbhost \
  libut_rendercontrol_dec \
  libutils \
  libv8 \
  libvariablespeed \
  libvex-x86-linux \
  libvideoeditor_3gpwriter \
  libvideoeditor_core \
  libvideoeditor_jni \
  libvideoeditor_mcs \
  libvideoeditor_osal \
  libvideoeditor_stagefrightshells \
  libvideoeditor_videofilters \
  libvideoeditorplayer \
  libvisualizer \
  libvold \
  libvorbisidec \
  libvpx \
  libwebcore \
  libwebp-decode \
  libwebp-encode \
  libwebrtc_aec \
  libwebrtc_aecm \
  libwebrtc_agc \
  libwebrtc_apm \
  libwebrtc_apm_utility \
  libwebrtc_audio_preprocessing \
  libwebrtc_ns \
  libwebrtc_resampler \
  libwebrtc_spl \
  libwebrtc_system_wrappers \
  libwebrtc_vad \
  libwilhelm \
  libwnndict \
  libwpa_client \
  libxml2 \
  libxslt \
  libxtables \
  libz \
  libz-host \
  libzipfile \
  lights.goldfish \
  lights.stingray \
  line_endings \
  linker \
  llvm-as \
  llvm-dis \
  llvm-ld \
  llvm-link \
  llvm-rs-cc \
  llvm-rs-link \
  local_time.default \
  logcat \
  logwrapper \
  make_cfst \
  make_ext4fs \
  make_g2g \
  make_ve_grammar \
  massif-x86-linux \
  mdnsd \
  mediaserver \
  memcheck-x86-linux \
  micro_bench \
  minigzip \
  mkbootfs \
  mkbootimg \
  mke2fs \
  mke2fs_host \
  mksdcard \
  mksh \
  mksnapshot \
  mkyaffs2image \
  modp_b64 \
  mtpd \
  nc \
  ndc \
  netcfg \
  netd \
  netperf \
  netserver \
  nfc.default \
  nfc.herring \
  none-x86-linux \
  obbtool \
  omx_tests \
  opcontrol \
  openssl \
  oprofiled \
  panorama_bench \
  parseStringTest \
  pbkdf2gen \
  perf \
  perfhost \
  perm_checker \
  pftest \
  ping \
  ping6 \
  post_trace \
  power.default \
  power.goldfish \
  procmem \
  procrank \
  profile_pid \
  profile_trace \
  q2dm \
  q2g \
  qemu-android-arm \
  qemu-android-x86 \
  qemu-props \
  qemud \
  racecheck_unittest \
  racoon \
  radiooptions \
  rand_emmc_perf \
  rawbu \
  read_addr \
  read_method \
  read_pid \
  read_trace \
  record \
  recordvideo \
  recovery \
  resize2fs \
  resize2fs_host \
  rgb2565 \
  rild \
  rs-spec-gen \
  rsg-generator \
  run-as \
  safe_iop_test \
  sane_schedstat \
  schedtest \
  scp \
  screencap \
  screenshot \
  sdcard \
  sensors.goldfish \
  sensors.herring \
  sensors.stingray \
  sensorservice \
  service \
  servicemanager \
  set_ext4_err_bit \
  setup_fs \
  sf2 \
  sftp \
  showlease \
  showmap \
  showslab \
  simg2img \
  skia_bench \
  skia_gm \
  skia_test \
  slang-data \
  slesTest_bassboostPath \
  slesTest_configbq \
  slesTest_decodeAac \
  slesTest_decodeToBuffQueue \
  slesTest_dim \
  slesTest_dual \
  slesTest_effectCapabilities \
  slesTest_engine \
  slesTest_eqFdPath \
  slesTest_eqOutputPath \
  slesTest_feedback \
  slesTest_getPositionUri \
  slesTest_intbufq \
  slesTest_loopUri \
  slesTest_manyPlayers \
  slesTest_monkey \
  slesTest_multiplay \
  slesTest_multithread \
  slesTest_object \
  slesTest_outputmix \
  slesTest_playFdPath \
  slesTest_playMuteSolo \
  slesTest_playStates \
  slesTest_playStreamType \
  slesTest_playUri \
  slesTest_playUri2 \
  slesTest_recBuffQueue \
  slesTest_reverb \
  slesTest_sawtoothBufferQueue \
  slesTest_seekTorture \
  slesTest_sendToPresetReverb \
  slesTest_slowDownUri \
  slesTest_srcsink \
  slesTest_urimime \
  slesTest_virtualizer \
  slesTest_xa \
  socketTag \
  sound \
  sqlite3 \
  ssh \
  ssh-keygen \
  sshd \
  ssltest \
  stack_dump \
  stagefright \
  strace \
  stream \
  su \
  surfaceflinger \
  sync_test \
  system_server \
  tblgen \
  tc \
  tcpdump \
  test-fb-refresh \
  test-fb-simple \
  test-librsloader \
  test-mdp \
  test-nusensors \
  test-opengl-codegen \
  test-opengl-configdump \
  test-opengl-fillrate \
  test-opengl-filter \
  test-opengl-finish \
  test-opengl-gl2_basic \
  test-opengl-gl2_copyTexImage \
  test-opengl-gl2_perf \
  test-opengl-gl2_yuvtex \
  test-opengl-gl_basic \
  test-opengl-gl_yuvtex \
  test-opengl-gralloc \
  test-opengl-linetex \
  test-opengl-swapinterval \
  test-opengl-textures \
  test-opengl-tritex \
  test-region \
  test-touchlag \
  test_algorithm_host \
  test_char_traits_host \
  test_functional_host \
  test_g2g \
  test_iomanip_host \
  test_ios_base_host \
  test_ios_pos_types_host \
  test_iostream_host \
  test_iterator_host \
  test_limits_host \
  test_list_host \
  test_memory_host \
  test_set_host \
  test_sstream_host \
  test_streambuf_host \
  test_string_host \
  test_swiarb \
  test_type_traits_host \
  test_uninitialized_host \
  test_vector_host \
  test_zipfile \
  testid3 \
  timeinfo \
  timetest \
  tinycap \
  tinymix \
  tinyplay \
  toolbox \
  triangleCM \
  triangleV2 \
  tsan-x86-linux \
  tst_str_parms \
  tune2fs \
  tune2fs_host \
  updater \
  usbtest \
  v8shell \
  valgrind \
  validatekeymaps \
  vdc \
  verifier_test \
  vgpreload_core-x86-linux \
  vgpreload_drd-x86-linux \
  vgpreload_helgrind-x86-linux \
  vgpreload_massif-x86-linux \
  vgpreload_memcheck-x86-linux \
  vgpreload_tsan-x86-linux \
  vold \
  wdsclient \
  webkitmerge \
  webrtc_apm_process_test \
  webrtc_apm_unit_test \
  whisperd \
  wifiLoadScanAssoc \
  xaVideoDecoderCapabilities \
  xaplay \
  zipalign \
  $(CLANG_TARGET)


# Check if CLANG_PREFIX is defined as an environment variable. Otherwise use the default one.
ifeq ($(CLANG_PREFIX),)
  CLANG_PREFIX=prebuilts/clang/$(HOST_PREBUILT_TAG)/x86/i686-android-linux-clang-trunk/bin/
endif

# Save the old values for TARGET|HOST variables that we are going to change
OLD_TARGET_CC:=$(TARGET_CC)
OLD_TARGET_CXX:=$(TARGET_CXX)
OLD_TARGET_AR:=$(TARGET_AR)
OLD_TARGET_LD:=$(TARGET_LD)
OLD_HOST_CC:=$(HOST_CC)
OLD_HOST_CXX:=$(HOST_CXX)
OLD_HOST_AR:=$(HOST_AR)
OLD_TARGET_GLOBAL_CFLAGS:=$(TARGET_GLOBAL_CFLAGS)

# Check if the current module is supported by clang.
ifneq ($(filter $(LOCAL_MODULE),$(clang_supported_targets)),)
  ifeq ($(or $(USE_CLANG),$(USE_DEVICE_CLANG)),1)
    TARGET_CC:=$(CLANG_PREFIX)clang_wrapper.py target c
    TARGET_CXX:=$(CLANG_PREFIX)clang_wrapper.py target cpp
    TARGET_AR:=$(CLANG_PREFIX)llvm-ar
    TARGET_LD:=$(CLANG_PREFIX)llvm-ld
    TARGET_GLOBAL_CFLAGS += -mllvm -post-RA-scheduler=false
  endif
  ifeq ($(or $(USE_CLANG),$(USE_HOST_CLANG)),1)
    HOST_CC:=$(CLANG_PREFIX)clang_wrapper.py host c
    HOST_CXX:=$(CLANG_PREFIX)clang_wrapper.py host cpp
    HOST_AR:=llvm-ar
  endif
endif
